import { expect, test } from '@playwright/test'

test('local setup, review gates and confirmed schedules work without provider calls', async ({ page, baseURL }, testInfo) => {
  const token = process.env.HARNESS_SMOKE_TOKEN ?? 'browser-smoke-token'
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('**/*', async route => {
    if (new URL(route.request().url()).origin !== new URL(baseURL!).origin) return route.abort()
    return route.continue()
  })
  await page.goto(`/#token=${encodeURIComponent(token)}`)
  await expect(page.getByRole('heading', { name: 'My fantasy team' })).toBeVisible()
  const state = await page.evaluate(async () => (await fetch('/api/state')).json())
  expect(state.settings.paused).toBe(true)
  expect(state.settings.mode).toBe('dry_run')
  expect(Object.values(state.credentials).every(value => value === false)).toBe(true)
  expect(state.active_run).toBeNull()
  expect(state.schedule.enabled).toBe(false)
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: 'Skip to main content' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('#main')).toBeFocused()
  await page.getByRole('button', { name: /Review my team/ }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Next: review the plan' }).click()
  await expect(page.getByRole('button', { name: 'Ask my coach' })).toBeDisabled()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: /Review my team/ })).toBeFocused()

  await page.getByRole('navigation').getByRole('button', { name: 'Connections', exact: true }).click()
  await expect(page.getByRole('note', { name: 'Live execution unavailable' })).toContainText('Advice only')
  await expect(page.getByRole('button', { name: 'Sign in to ESPN', exact: true })).toBeVisible()
  await page.getByLabel('Model ID').fill('invalid model id')
  await page.getByRole('button', { name: 'Save manager settings' }).click()
  await expect(page.getByRole('alert')).toContainText('model')
  await page.getByLabel('Model ID').fill('smoke-local-model')
  await page.getByRole('button', { name: 'Save manager settings' }).click()
  await expect(page.getByText('Manager settings saved.', { exact: true })).toBeVisible()
  const grokCard = page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'Grok · xAI', exact: true }) })
  await grokCard.getByLabel('Credential', { exact: true }).fill('not-a-real-key-smoke-test')
  await grokCard.getByRole('button', { name: 'Save securely', exact: true }).click()
  await expect(grokCard.getByLabel('Replace credential', { exact: true })).toHaveValue('')
  await grokCard.getByRole('button', { name: 'Remove', exact: true }).click()
  await grokCard.getByRole('button', { name: 'Remove credential', exact: true }).click()
  await expect(grokCard.getByText('Credential removed.', { exact: true })).toBeVisible()

  await page.getByRole('navigation').getByRole('button', { name: 'Check-in schedule', exact: true }).click()
  await expect(page.getByLabel('Let my coach check in automatically')).toBeDisabled()
  await page.getByText('Custom timing and timezone', { exact: true }).click()
  await page.getByLabel('Minutes between reviews').fill('90')
  await page.getByLabel('Timezone', { exact: true }).fill('UTC')
  await page.getByRole('button', { name: 'Review schedule', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Automatic check-ins will be off.')
  await page.getByRole('button', { name: 'Go back', exact: true }).click()
  await page.getByRole('button', { name: 'Review schedule', exact: true }).click()
  await page.getByRole('button', { name: 'Save schedule', exact: true }).click()
  await expect(page.getByText('Check-in schedule saved.', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('navigation').getByRole('button', { name: 'Check-in schedule', exact: true }).click()
  await page.getByText('Custom timing and timezone', { exact: true }).click()
  await expect(page.getByLabel('Minutes between reviews')).toHaveValue('90')
  await expect(page.getByLabel('Timezone', { exact: true })).toHaveValue('UTC')
  await expect(page.getByLabel('Let my coach check in automatically')).not.toBeChecked()

  await page.getByRole('button', { name: 'Emergency pause', exact: true }).click()
  await page.getByRole('navigation').getByRole('button', { name: 'Decisions', exact: true }).click()
  await page.getByText('Behind the scenes: activity and troubleshooting', { exact: true }).click()
  await expect(page.getByRole('region', { name: 'Workspace and scheduler activity' }).locator('.timeline > li').first()).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('connections-and-history.png'), fullPage: true })
  expect(await page.evaluate(() => Object.keys(localStorage))).toEqual([])
  expect(await page.evaluate(() => Object.keys(sessionStorage))).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('rejected local login recovers without exposing credentials', async ({ page }) => {
  const token = process.env.HARNESS_SMOKE_TOKEN ?? 'browser-smoke-token'
  await page.goto('/')
  await expect(page.getByLabel('Local access token')).toBeVisible()
  await page.getByLabel('Local access token').fill('invalid-local-token')
  await page.getByRole('button', { name: /Connect to local app/ }).click()
  await expect(page.getByRole('alert')).toContainText('Invalid local launch token')
  await expect(page.getByLabel('Local access token')).toHaveValue('')
  await page.getByLabel('Local access token').fill(token)
  await page.getByRole('button', { name: /Connect to local app/ }).click()
  await expect(page.getByRole('heading', { name: 'My fantasy team' })).toBeVisible()
})
